### ISSUE TITLE
Create ESLint autofix for eslint-plugin-react/jsx-first-prop-new-line

### ISSUE THREAD

**Issue by shioju** [idagds/eslint-plugin-react#1]
## What we want

As a user, I want an autofix for the [react/jsx-first-prop-new-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md) rule.
## General acceptance criteria

Appropriate tests should be written for each additional feature.

Any additional code must not break the CI for any build configuration.

As we do not own the project, the task is considered done once your pull request has been merged into [idagds/eslint-plugin-react](https://github.com/idagds/eslint-plugin-react). To benefit the rest of the open source community, we strongly encourage you to also submit a pull request to [yannickcr/eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react).
## Additional information

[Developer guide for writing an autofix](http://eslint.org/docs/developer-guide/working-with-rules#applying-fixes)

**Comment by snowypowers** [comment]
hi FYI, the pull request for this fix is merged into the parent repo but contains adjustments of their opinion.
They did not want an indentation fix and felt that running the linter a second time to fix the indentation was ok. If you all are going to merge from parent, please note that the arguments remain as original (one for style).
